import { Injectable } from '@angular/core';
import { Karyawan } from './karyawan';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/781213f4e7144a98b56f76bd9f7809b4'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) {}

  getKaryawans() {
    return this.http.get(`${this.baseUrl}/karyawan`);
  }

  getKaryawan(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/karyawan/${id}`);
  }

  postKaryawan(karyawan: Karyawan) {
    delete karyawan._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/karyawan`, karyawan);
  }

  updateKaryawan(karyawan: Karyawan) {
    const id = karyawan._id; // we copy the original id
    delete karyawan._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/karyawan/${id}`, karyawan);
  }

  deleteKaryawan(karyawan: Karyawan) {
    const id = karyawan._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/karyawan/${id}`);
  }
}
